import React from 'react';

export default function LimitationsSection() {
  return (
    <section id="section-6" className="w-full py-24 bg-[#0a0a0a] text-white">
      <div className="max-w-7xl mx-auto px-8 md:px-16 lg:px-0">
        <div className="mb-16">
          <h2 className="text-3xl md:text-4xl font-serif font-bold mb-6 text-red-500">
            The Boundary of Knowledge
          </h2>
          <p className="text-gray-400 max-w-4xl leading-relaxed text-lg">
            It must be candidly pointed out that the framework proposed in this paper has limitations at the methodological level. The failure of any module in the pipeline will lead to a decline in overall performance. For instance, if the panoramic image generated by MVDiffusion has severe distortions, subsequent stages cannot correct it. Moreover, the current information flow is unidirectional, lacking a mechanism to back-propagate optimization from Stage 4 to Stages 1-3. Additionally, the current design is aimed at closed indoor scenes, and the spherical coordinate system parameterization is not suitable for unbounded outdoor environments. The above limitations point out the direction for future improvements.
          </p>
        </div>
      </div>
    </section>
  );
}
